FROM python:3.12-slim

WORKDIR /locust

COPY locustfile.py /locust
COPY requirements.txt /locust

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8089

CMD ["locust", "-f", "locustfile.py"]
