apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml -o kubernetes-manifests/ --volumes hostPath
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: airflow-init
  name: airflow-init
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: airflow-init
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f docker-compose.yml -o kubernetes-manifests/ --volumes hostPath
        kompose.version: 1.26.0 (40646f47)
      labels:
        io.kompose.network/proyecto-2-default: "true"
        io.kompose.service: airflow-init
    spec:
      containers:
        - args:
            - -c
            - |
              # Run DB migrations and create default user
              exec /entrypoint bash -c "
                airflow db migrate &&
                airflow users create \
                  --username airflow \
                  --firstname Airflow \
                  --lastname Admin \
                  --role Admin \
                  --email admin@example.com \
                  --password airflow
              "
          command:
            - /bin/bash
          env:
            - name: AIRFLOW__API__AUTH_BACKENDS
              value: airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session
            - name: AIRFLOW__CELERY__BROKER_URL
              value: redis://:@redis:6379/0
            - name: AIRFLOW__CELERY__RESULT_BACKEND
              value: db+postgresql://airflow:airflow@postgres/airflow
            - name: AIRFLOW__CELERY__WORKER_HOSTNAME
              value: worker@%h
            - name: AIRFLOW__CELERY__WORKER_LOG_LEVEL
              value: INFO
            - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
              value: "true"
            - name: AIRFLOW__CORE__EXECUTOR
              value: CeleryExecutor
            - name: AIRFLOW__CORE__FERNET_KEY
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: "false"
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://airflow:airflow@postgres/airflow
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://airflow:airflow@postgres/airflow
            - name: AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK
              value: "true"
            - name: AIRFLOW__WEBSERVER__SECRET_KEY
            - name: AWS_ACCESS_KEY_ID
              value: admin
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            - name: AWS_S3_FORCE_PATH_STYLE
              value: "true"
            - name: AWS_SECRET_ACCESS_KEY
              value: supersecret
            - name: BATCH_SIZE
              value: "15000"
            - name: DB_HOST
              value: mysql-db
            - name: DB_NAME
              value: training
            - name: DB_PASSWORD
              value: password
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: user
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://minio:9000
            - name: MLFLOW_TRACKING_URI
              value: http://mlflow:8003
            - name: MODELS_DIR
              value: /models
            - name: PREDICT_API_URL
              value: http://api
            - name: PYTHONPATH
              value: /opt/airflow:/opt/airflow/dags:/opt/airflow/plugins
            - name: _AIRFLOW_DB_UPGRADE
              value: "true"
            - name: _AIRFLOW_WWW_USER_CREATE
              value: "true"
            - name: _AIRFLOW_WWW_USER_PASSWORD
              value: airflow
            - name: _AIRFLOW_WWW_USER_USERNAME
              value: airflow
            - name: _PIP_ADDITIONAL_REQUIREMENTS
          image: javieresquivel123/airflowdiabetes:v1.0
          name: airflow-init
          volumeMounts:
            - mountPath: /sources
              name: airflow-init-hostpath0
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /home/ubuntu/Proyects/MLOPS_Talleres/mlops/proyecto_2
          name: airflow-init-hostpath0
