apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml -o kubernetes-manifests/ --volumes hostPath
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: locust
  name: locust
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: locust
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f docker-compose.yml -o kubernetes-manifests/ --volumes hostPath
        kompose.version: 1.26.0 (40646f47)
      labels:
        io.kompose.network/proyecto-2-default: "true"
        io.kompose.service: locust
    spec:
      containers:
        - env:
            - name: LOCUST_HOST
              value: http://api:80
          image: locust
          name: locust
          ports:
            - containerPort: 8089
              hostPort: 8089
              protocol: TCP
      restartPolicy: Always
