services:

  locust:
    build:
      context: .
      dockerfile: Dockerfile.locust
    container_name: locust
    ports:
      - "8089:8089"

    environment:
      - LOCUST_HOST=http://app:80
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

networks:
  mlops-net:
    external: true