apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/javier/Descargas/kompose convert -f docker-compose.yml -o komposefiles/ --volumes hostPath
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /home/javier/Descargas/kompose convert -f docker-compose.yml -o komposefiles/ --volumes hostPath
        kompose.version: 1.26.0 (40646f47)
      labels:
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: mysql-db
            - name: DB_NAME
              value: training
            - name: DB_PASSWORD
              value: password
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: user
            - name: MLFLOW_TRACKING_URI
              value: http://mlflow:8003
            - name: MODELS_DIR
              value: /app/models
            - name: MODEL_NAME
              value: real-estate-model
            - name: MODEL_STAGE
              value: prod
          image: javieresquivel123/proyecto-final-api:latest
          name: api
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/models
              name: api-hostpath0
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /home/javier/Documentos/programacion/maestria/mlops/proyecto_final/models
          name: api-hostpath0
