apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: final
  annotations:
    kompose.cmd: /home/javier/Descargas/kompose convert -f docker-compose.yml -o komposefiles/ --volumes hostPath
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /home/javier/Descargas/kompose convert -f docker-compose.yml -o komposefiles/ --volumes hostPath
        kompose.version: 1.26.0 (40646f47)
      labels:
        io.kompose.service: api
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.36
          command:
            - "sh"
            - "-c"
            - "until nc -zvw1 mysql-db 8005; do echo 'Esperando a que MySQL levante...'; sleep 2; done;"

      containers:
        - env:
            - name: DB_HOST
              value: mysql-db
            - name: DB_NAME
              value: training
            - name: DB_PASSWORD
              value: password
            - name: DB_PORT
              value: "8005"
            - name: DB_USER
              value: user
            - name: MLFLOW_TRACKING_URI
              value: http://mlflow:8003
            - name: MODELS_DIR
              value: /app/models
            - name: MODEL_NAME
              value: real-estate-model
            - name: MODEL_STAGE
              value: prod
          image: javieresquivel123/proyecto-final-api:66b889591b43d1d77b3b89ac8cef46ca3562c3c7
          imagePullPolicy: Always
          name: api
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/models
              name: api-hostpath0
          resources:
            requests:
              cpu: "1"      # Reserva 0.25 CPUs
              memory: "500Mi"    # Reserva 64 Megabytes
            limits:
              memory: "2000Mi"
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /home/javier/Documentos/programacion/maestria/mlops/proyecto_final/models
          name: api-hostpath0
