apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: final
  annotations:
    kompose.cmd: /home/javier/Descargas/kompose convert -f docker-compose.yml -o komposefiles2/ --volumes hostPath
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: locust
  name: locust
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: locust
  template:
    metadata:
      annotations:
        kompose.cmd: /home/javier/Descargas/kompose convert -f docker-compose.yml -o komposefiles2/ --volumes hostPath
        kompose.version: 1.26.0 (40646f47)
      labels:
        io.kompose.service: locust
    spec:
      containers:
        - env:
            - name: LOCUST_HOST
              value: http://api:8013
          image: javieresquivel123/proyecto-final-locust:fb5d4fd567c3f5ed2c7d0befb742b84474484aed
          imagePullPolicy: Always
          name: locust
          resources:
            requests:
              cpu: "500m"      # Reserva 0.25 CPUs
              memory: "250Mi"    # Reserva 64 Megabytes
            limits:
              cpu: "2"         # Máximo 1 CPU
              memory: "500Mi"
          ports:
            - containerPort: 8089
              protocol: TCP
      restartPolicy: Always
