apiVersion: v1
kind: Service
metadata:
  namespace: final
  annotations:
    kompose.cmd: /home/javier/Descargas/kompose convert -f docker-compose.yml -o komposefiles2/ --volumes hostPath
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: prometheus
  name: prometheus
spec:
  ports:
    - name: "9090"
      port: 9090
      targetPort: 9090
  selector:
    io.kompose.service: prometheus
