apiVersion: v1
kind: Service
metadata:
  namespace: final
  annotations:
    kompose.cmd: /home/javier/Descargas/kompose convert -f docker-compose.yml -o komposefiles2/ --volumes hostPath
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: streamlit
  name: streamlit
spec:
  ports:
    - name: "8050"
      port: 8050
      targetPort: 8501
  selector:
    io.kompose.service: streamlit
